-f

diff --git a/bin/gitpush b/bin/gitpush
--- a/bin/gitpush
+++ b/bin/gitpush
@@ -1,27 +1,26 @@
 #!/bin/bash
 
-while getopts ":f" opt; do
-  case ${opt} in
-    f )
+if [ $# -lt 1 ]
+then
+  echo "No commit message supplied"
+  exit 1
+fi
+
+COMMIT_MESSAGE="$1"
+shift
+
+while getopts "f" opt
+do
+  case $opt in
+    f)
       FORCE_MERGE=true
       ;;
-    \? )
-      echo "Invalid option: -$OPTARG" 1>&2
-      exit 1
-      ;;
-    : )
-      echo "Option -$OPTARG requires an argument" 1>&2
+    \?)
+      echo "Invalid option: -$OPTARG" >&2
       exit 1
       ;;
   esac
 done
-shift $((OPTIND -1))
-
-if [ $# -eq 0 ]
-  then
-    echo "No commit message supplied"
-    exit 1
-fi
 
 GITADD="git add ."
 echo "[INFO] ${GITADD}"
@@ -34,7 +33,7 @@ GITPUSH="git push -u origin head"
 echo $GITPUSH
 $GITPUSH
 
-if [ -n "$FORCE_MERGE" ]
+if [ "$FORCE_MERGE" = true ]
   then
     echo "[INFO] Creating pull request"
     gh pr create --title "$1" --body "$1" --base main
